### ISSUE TITLE
2.6

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/Si2015Tim4#11]
"Svaki odgovor koji nije isključivo pozitivan odnosno negativan se ne smatra validnim odgovorom." Previše striktno. Šta ako ga želite pitati hoće li opciju A, B ili C. Objašnjenja su svakako dobrodošla.
Sve ostalo je striktno 48 sati, "u što kraćem roku" je poprilično labavo (može i godina dana).

**Comment by Hadziarapovic** [comment]
Nisam shvatila ovaj drugi dio komentara. 48h je previše striktno, a "u što kraćem roku" je labavo?

**Comment by deancupovic** [comment]
Na više mjesta kažete: u roku 48 sati...
a onda kažete: "Razvojni tim je dužan u što kraćem roku odgovoriti ..."
