### ISSUE TITLE
Ulazi i izlazi

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/Si2015Tim4#29]
Niste dobro razumjeli koncpet. Nigdje nemate evidenciju ulaza i izlaza. Npr:

1. Ulaz broj 1: 100 čokolada po cijeni 1 KM i 50 keksova po cijeni 2 KM. Stanje: 100 čokolada po cijeni 1 KM, 50 keksova: 2KM.
2. Ulaz broj 2: 300 čokolada po cijeni 0,9 KM i 100 litara mlijeka po cijeni 0,8 KM. Stanje 400 čokolada po cijeni 0,925 KM; 50 keksova 2 KM; 100 litara mlijeka: 0,8 KM
3. Izlaz broj 1: 100 čokolada po bilo kojoj cijeni. Stanje 300 čokolada po cijeni 0,925; 50 keksova 2 KM; 100 litara mlijeka: 0,8 KM
4. Inventura 295 čokolada, 50 keksova, 105 litara mlijeka. 
5. Obračun inventure napravi dokument viška sa 5 litara mlijeka; dokument manjka sa 5 čokolada. Novo stanje: 295 čokolada po cijeni 0,925; 50 keksova 2 KM; 105 litara mlijeka: 0,8 KM

Jedino dokument ulaza utiče na ponderisanu nabavnu cijenu.

**Comment by Hadziarapovic** [comment]
Ne shvatam šta je pogrešno u prikazu FZ. Ulazni podaci je roba na stanju sa cijenama,izlazi su upravo ti dokumenti. S tim da sam promijenila da se porede ulazi i izlazi, možda nije bilo dovoljno jasno napisano.

**Comment by deancupovic** [comment]
Meni nije bilo jasno, zato sam i stavio komentar.
