### ISSUE TITLE
Dugme Kraj na login screenu nema funkciju

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#35]
Komponenta:
Inventura.LogInScreen

commit ID:
8417bbc

Opis problema:
Klikom na dugme Kraj nista se ne desava.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. Kliknuti na dugme Kraj.

Dobijeni rezultat:
- Nema rezultata.

Očekivani rezultat:
- Dispose forme.

**Comment by Hadziarapovic** [comment]
Popravljeno.
