### ISSUE TITLE
Error pri brisanju klase artikala

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#43]
Komponenta:
BrisanjeKlaseArtikalGUI

commit ID:
8417bbc

Opis problema:
Prilikom brisanja klase artikla desi se greska.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa privilegijama Sefa.
2. U Meni-u izabrati opciju Administracija->Klase artikala->Brisanje
3. U textbox unijeti postojecu klasu artikala:
(slika baze)
![image](https://cloud.githubusercontent.com/assets/11327927/15277707/11b13594-1b0c-11e6-9a2f-681f73f67637.png)

Dobijeni rezultat:
Obavjestenje o nemogucnosti izvrsenja:
![image](https://cloud.githubusercontent.com/assets/11327927/15277710/2137c276-1b0c-11e6-8c41-666f4b69cd8e.png)

Ocekivani rezultat:
Izbrisana klasa artikala.

**Comment by sibrahimpa1** [comment]
Rijeseno kroz issue #72.

**Comment by emhuskic** [comment]
Ovaj issue je prije napisan.
