### ISSUE TITLE
Lose handle-ana obavjestenja u modifikaciji artikla

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#45]
Komponenta:
ModifikacijaArtiklaGUI

commit ID:
8417bbc

Opis problema:
Prilikom unosa neispravnih vrijednosti u polja Kolicina i Cijena, pojavljuju se nedovoljno objasnjena upozorenja.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa privilegijama Sefa.
2. U Meni-u izabrati opciju Administracija->Artikli->Modifikacija
3. U textbox za kolicinu upisati string (ne broj)

Dobijeni rezultat:
For input string: "em"..
![image](https://cloud.githubusercontent.com/assets/11327927/15277740/b333065e-1b0c-11e6-9fed-e7b59dc1cb38.png)

Ocekivani rezultat:
Pravilno obavjestenje o pogresnom unosu.

**Comment by sibrahimpa1** [comment]
Rijeseno kroz issue #40.
