### ISSUE TITLE
Nema validacija prilikom unosa novog korisnika

### ISSUE THREAD

**Issue by kbalic1** [SoftverInzenjeringETFSA/Si2015Tim4#46]
Komponenta:
RegistracijaNovogKorisnika

commit ID:
8417bbc

Opis problema:
Prilikom unosa novog korisnika nema validacija i u bazu se upise novi korisnik bez podataka.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. U Meni-u izabrati opciju Administracija -> Korisnici -> Unos.
3. Pritisnuti dugme Unesi .

Dobijeni rezultat:

U bazi je unesen novi korisnik bez podataka.
![novikorisnik](https://cloud.githubusercontent.com/assets/10118023/15277750/f18651b8-1b0c-11e6-9e6d-6cc57023ddd8.jpg)

Očekivani rezultat:

Ocekivala e validacija polja za unos i blokiranje unosa novog korisnika 

bez podataka.

**Comment by sibrahimpa1** [comment]
Rijeseno kroz issue #38.
