### ISSUE TITLE
Unos negativne kolicine pri modifikaciji artikla

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#47]
Komponenta:
ModifikacijaArtiklaGui

commit ID:
8417bbc

Opis problema:
Prilikom dodavanja negativne kolicine artikala nema validacije.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa privilegijama Sefa.
2. U Meni-u izabrati opciju Administracija->Artikli->Modifikacija
3. U textbox za kolicinu upisati negativan broj (npr. -3)

Dobijeni rezultat:
Uspjesno modificiran artikal sa negativnom kolicinom artikala
![image](https://cloud.githubusercontent.com/assets/11327927/15277749/efda4540-1b0c-11e6-8f82-c57154f5c377.png)
Stanje u bazi:
![image](https://cloud.githubusercontent.com/assets/11327927/15277756/0950627a-1b0d-11e6-879e-d14cfa9e745a.png)

Ocekivani rezultat:
Obavjestenje o pogresnom unosu kolicine i nemogucnost modifikacije artikla.

**Comment by Hadziarapovic** [comment]
Radi
