### ISSUE TITLE
Zakljucivanje dokumenata bez artikala 

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#50]
Komponenta:
IzlazniDokument

commit ID:
8417bbc

Opis problema:
Moze se dodati dokument izlaza i otpisa bez artikala na koje se odnosi.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa privilegijama Sef.
2. U Meni-u izabrati opciju Dokumenti->Kreiraj novi
3. Ne izabrati nijedan artikal
4. Kliknuti na dugme Zakljuci dokument

Dobijeni rezultat:
Kreiran dokument:
![image](https://cloud.githubusercontent.com/assets/11327927/15277840/dade8bfe-1b0e-11e6-8e14-12e28daaf670.png)

Ocekivani rezultat:
Prijava greske.

**Comment by Hadziarapovic** [comment]
Ovo je u sustini ok u smislu da izlaz ostaje 0 i ne mijenja se stanje na skladištu. Stavila sam upozorenje za svaki slučaj.
