### ISSUE TITLE
Funkcionalnost Evidencije ostecene robe nije implementirana

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#57]
SRS clan 2.2.10:
![image](https://cloud.githubusercontent.com/assets/11327927/15278117/22b3b6d4-1b14-11e6-9563-92572ce5bdde.png)
Funkcionalnost nije implementirana.

**Comment by Hadziarapovic** [comment]
Dijagram je prikazan na slici ispod. Prebrojavanje se vrši ručno, ponderisana cijena se ne računa jer je korisnik promjenio FZ. Kreiranje izvjestaja/dokumenta tipa otpis postoji kao i njegovo pohranjivanje u bazu. (Kreira se na isti način kao i izlazni dokument, sa opcijom u combo box u kojem biramo tip dokumenta.) 
![image](https://cloud.githubusercontent.com/assets/11289714/15407147/cb461b78-1e09-11e6-90b4-7468b21f3e14.png)
