### ISSUE TITLE
Funkcionalnost Promjena lozinke nije u skladu sa SRS dokumentom

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#58]
Prema funkcionalnosti 3.2.5 u SRS dokumentu, za promjenu lozinke korisnik treba unijeti:
![image](https://cloud.githubusercontent.com/assets/11327927/15278158/c8e398c6-1b14-11e6-9883-931eeaa93eb8.png)
U implementaciji, potrebno je unijeti samo staru lozinku, te dva puta novu:
![image](https://cloud.githubusercontent.com/assets/11327927/15278163/db06a674-1b14-11e6-94ea-e0acd08b53e1.png)

**Comment by psimanic1** [comment]
Riješen "bug" dodavanjem traženih polja.
Commit ID: 2c97eea
