### ISSUE TITLE
Funkcionalnost pretrage artikala po klasi nije implementirana

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#60]
U clanu 3.2.7 dokumenta SRS pise da je od esencijalne vaznosti kreiranje liste artikala na osnovu klase kojoj pripadaju. Funkcionalnost nije implementirana.
![image](https://cloud.githubusercontent.com/assets/11327927/15278203/6bc2a636-1b15-11e6-8c0e-aa6be14701c2.png)

**Comment by Hadziarapovic** [comment]
Sada implementirano.
