### ISSUE TITLE
Moguce dodati dva zaposlenika sa istim username-om

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#61]
Komponenta:
RegistracijaNovogKorisnika

commit ID:
8417bbc

Opis problema:
Moguce je dodati dva korisnika sa istim korisnickim imenom. 

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa privilegijama Sef.
2. U Meni-u izabrati opciju Administracija->Korisnici->Unos
3. Ispuniti formu tako da je polje za Korisnicko ime ispunjeno korisnickim imenom koji postoji u bazi.

Dobijeni rezultat:
Uspjesno unesen korisnik.
Stanje u bazi:
![image](https://cloud.githubusercontent.com/assets/11327927/15278247/2cf8cb82-1b16-11e6-8167-e8b05a061c5f.png)

Ocekivani rezultat:
Prijava greske.

**Comment by sibrahimpa1** [comment]
Rijeseno kroz issue #78.

**Comment by emhuskic** [comment]
Opet, ovaj issue je prije napisan, pa je issue 78 duplikat ovog.
