### ISSUE TITLE
Pregled dokumenata manjka i viska ne rade nista

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#65]
Komponenta:
GlavniInterfejs

commit ID:
8417bbc

Opis problema:
Klikom na pregled dokumenata manjka i pregled dokumenata viska - ne prikazuje se nista.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa privilegijama Sef.
2. U Meni-u izabrati opciju Dokumenti->Pregled dokumenata manjka / Dokumenti->Pregled dokumenata viska

Dobijeni rezultat:
Nikakav.

Ocekivani rezultat:
Dokument manjka/viska.

**Comment by Hadziarapovic** [comment]
Bug nije validan. Očekivano je da se testeri prije svega informišu i upute u funkcionalnosti sistema. Naravno da ne ispisuje ništa za dokumente viška i manjka, ako prethodno nisu kreirani obračunom inventure, tj. automatski ne postoje ni u bazi. Savjetujemo da prvo uradite inventuru korektno, zaključivanje i obradu, te nakon toga izlistate navedene dokumente.
