### ISSUE TITLE
Nakon jednog unosa skladista vise se ne moze unijeti

### ISSUE THREAD

**Issue by kbalic1** [SoftverInzenjeringETFSA/Si2015Tim4#68]
Komponenta:
UnosSkladistaGUI

commit ID:
8417bbc

Opis problema:
Nakon prvog unosa skladista vise se skladiste ne moze unijeti.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa privilegijama Sef.
2. U Meni-u izabrati opciju Skladiste->Unos skladista
3. Ispunit formu i pritisnut dugme Unesi

Dobijeni rezultat:
Skladiste se nije unijelo u bazu
![unosdrugog](https://cloud.githubusercontent.com/assets/10118023/15278561/9f4d7f6c-1b1a-11e6-9c04-0d0102060d54.jpg)

Ocekivani rezultat:
Uspjesan unos skladista

**Comment by sibrahimpa1** [comment]
Ovaj issue je dupli, Emina je vec navela problem koji se javlja nakon prvog unosa skladista.
