### ISSUE TITLE
Izuzetak pri unosu skladista

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#69]
Komponenta:
UnosSkladistaGUI

commit ID:
8417bbc

Opis problema:
Izuzetak prilikom unosa skladista.

2. U Meni-u izabrati opciju Skladiste->Unos skladista
3. Ispuniti formu i pritisnuti dugme Unesi
![image](https://cloud.githubusercontent.com/assets/11327927/15278618/517aac78-1b1b-11e6-8be6-542df86f6f7f.png)

Dobijeni rezultat:
Skladiste se nije unijelo u bazu
![image](https://cloud.githubusercontent.com/assets/11327927/15278625/7029c442-1b1b-11e6-9f7a-b54e00f5018a.png)

Ocekivani rezultat:
Uspjesan unos.

**Comment by Hadziarapovic** [comment]
Ukoliko si pročitala SRS vidjela si da korisnik nije tražio tu funkcionalnost, te je ista bila rezultat dobre volje tima.
