### ISSUE TITLE
Nedostatak validacija kod registracije novog korisnika

### ISSUE THREAD

**Issue by TheAdnan** [SoftverInzenjeringETFSA/Si2015Tim4#73]
**Komponenta**: RegistracijaNovogKorisnika

**commit id:** c9df18a86da73ca5d6808713d845fb73e55b4bea

**Opis problema:** Nedostatak validacija kod registracije korisnika. Za ime i prezime se mogu unijeti brojevi, za JMBG se moze unijeti manje od 13 znakova (i mogu i slova i brojevi) i sl. (28. str u SRS-u), kao što vidimo na slici
	1. Administracija->Korisnici-> Unos
	2. Unesemo podatke i klik na registruj button
	
![screenshot_1](https://cloud.githubusercontent.com/assets/7202517/15288592/2c77f524-1b6c-11e6-900e-0a3c61c7a719.jpg)

**Dobijeni rezultat:**
	Dodan korisnik, ali bez ikakvih validacija i restrikcija pri unosu

**Očekivani rezultat:**
	Dodan korisnik ali s validiran podacima za sva polja

**Comment by sibrahimpa1** [comment]
Rijeseno kroz issue #46.
