### ISSUE TITLE
Razlika u krajnjem dizajnu i u UIS

### ISSUE THREAD

**Issue by TheAdnan** [SoftverInzenjeringETFSA/Si2015Tim4#74]
**commit id:** 7e50c6be994bea81829b1996cca4d4f68d7ecddf

**Opis problema:** Razlika između dizajna aplikacije u SRS-u i kranjeg dizajna aplikacije
Unutar SRS (17-25 str.) je znatno drugačiji dizajna od trenutnog dizajna aplikacije. Npr:
	
![screenshot_1](https://cloud.githubusercontent.com/assets/7202517/15288610/49ed3a38-1b6c-11e6-9013-904a5c25c78e.jpg)

![screenshot_2](https://cloud.githubusercontent.com/assets/7202517/15288632/664a3488-1b6c-11e6-931d-e5a7ee7e0b6a.jpg)

**Dobijeni rezultat:**
	Različit dizajn interfejsa

**Očekivani rezultat:**
	Isti ili sličan dizajn interfejsa kao u SRS-u

**Comment by Hadziarapovic** [comment]
Već prijavljeno.
