### ISSUE TITLE
Nema povratne informacije o bezuspješnoj promijeni lozinke

### ISSUE THREAD

**Issue by kprses** [SoftverInzenjeringETFSA/Si2015Tim4#76]
Komponenta: PromjenaLozinke

commit ID:
c9df18a86da73ca5d6808713d845fb73e55b4bea

Koraci za reproduciranje problema:
1. Pokretanje desktop aplikacije "Inventura"
2. Odabir opcije "Promijeni lozinku" iz menija "Postavke" koji se nalazi u menubaru
3. Unos trenutne lozinke
4. Unos nove lozinke u polje nova lozinka
5. Unos nove lozinke u polje potvrda nove lozinke (različite od lozinke unesene u polje nova lozinka)
6. Klik na dugme "Potvrdi"

Dobijeni rezultat:
![image](https://cloud.githubusercontent.com/assets/11404450/15306163/9388eda2-1bc8-11e6-822d-77a973a5e85b.png)

Nikakva promjena na formi se nije desila, odnosno korisnik nema povratnu informaciju da je uspješno ili bezuspješno promijenjena lozinka.

Očekivani rezultat:
Očekivani rezultat je neki Message Box sa informacijom da se unosi nove lozinke ne poklapaju.

**Comment by sibrahimpa1** [comment]
Ispravljeno kroz issue #71.
