### ISSUE TITLE
Neslaganje sa dokumentacijom (SRS i intervju sa naručiocem softvera)

### ISSUE THREAD

**Issue by kprses** [SoftverInzenjeringETFSA/Si2015Tim4#79]
Komponente: DodavanjeArtikla, GlavniInterfejs

Prema intervjuu naručioc softvera je zahtijevao da svaki artikal ima svoju klasu:
![intervjusviartikli](https://cloud.githubusercontent.com/assets/11404450/15307085/1d2997f8-1bd0-11e6-9b66-a18f89930855.jpg)

U SRS-u F.Z. 3.2.6 kao ulaz uzima klasu artikla
![srsartikalklasa](https://cloud.githubusercontent.com/assets/11404450/15307225/49979bf4-1bd1-11e6-821e-5c9332fea691.jpg)

commit ID:
c9df18a86da73ca5d6808713d845fb73e55b4bea

Koraci za reproduciranje problema:
1. Pokretanje desktop aplikacije "Inventura"
2. Odabir opcije "Unos" sa opcije Artikli. (Administracija -> Artikli -> Unos)
3. Popunjavanje podataka za artikal (izuzev klase artikla)
4. Klik na dugme "Dodaj"

![ssbezklase](https://cloud.githubusercontent.com/assets/11404450/15307091/301df624-1bd0-11e6-8ece-3ae924933849.jpg)

Dobijeni rezultat:
Na listi artikala se prikazuju artikli bez klase
![dobijenirezultat](https://cloud.githubusercontent.com/assets/11404450/15307075/0a1037bc-1bd0-11e6-956a-eb9c59305ba5.jpg)

Očekivani rezultat:
Očekivani rezultat je poruka da se desila greška ili zabrana unošenja artikla bez klase artikla.

**Comment by sibrahimpa1** [comment]
Rijeseno kroz issue #40.
