### ISSUE TITLE
Pogrešna poruka greške

### ISSUE THREAD

**Issue by kprses** [SoftverInzenjeringETFSA/Si2015Tim4#80]
Komponenta: LogInScreen

commit ID:
cc43473d06d1801275624116e24ce9bbcf3789e0

Opis problema:
Ukoliko se desi slučaj da u bazi podataka imamo dva reda sa identičnim korisničkim imenom i lozinkom (to se može desiti kroz unos novog korisnika sa već postojećim pristupnim podacima). Ako se pokušamo logovati sa podacima koji se dupliciraju u bazi podataka, javlja nam se pogrešna poruka greške.

Koraci za reproduciranje problema:
1. Pokretanje desktop aplikacije "Inventura"
2. Unos korisničkog imena (koja postoji u bazi) 
3. Unos lozinke (koja postoji u bazi) 
4. Klik na dugme "Prijava"

Dobijeni rezultat:
![loginprikaz](https://cloud.githubusercontent.com/assets/11404450/15307942/639e32b8-1bd8-11e6-95ab-0302c9ede340.jpg)
Rezultat je poruka sa greškom "Korisnicko ime ili lozinka nisu tačni" iako su i korisničko ime i lozinka tačni.

Stanje u bazi podataka:
![stanjezeba](https://cloud.githubusercontent.com/assets/11404450/15308022/11df0334-1bd9-11e6-870d-fdb4e08ba956.jpg)

Očekivani rezultat:
Očekivani rezultat je drugačija poruka greške. Npr. "Uneseno korisničko ime je duplikat. Molimo kontaktirajte administratora"

**Comment by sibrahimpa1** [comment]
Rijeseno kroz issue #78 (vise nije moguce dodati 2 korisnika sa istim podacima).

**Comment by kprses** [comment]
Možda jeste riješeno kroz ovaj issue 78, ali ne mislim da je duplikat, mislim da je bio novi bug.
