### ISSUE TITLE
Funkcionalni zahtjev: Evidencija artikla nije (korektno) implementirana

### ISSUE THREAD

**Issue by kprses** [SoftverInzenjeringETFSA/Si2015Tim4#81]
Komponenta: GlavniInterfejs

Opis problema:
F.Z. 3.2.8 nije implementirana tj. nigdje u aplikaciji korisnik ne može dobiti izlaze navedene u ovom funkcionalnom zahtjevu tj. izvještaj za propisane artikle, sa navedenim bar kodom, nazivom, količinom i cijenom.

![fznijeimplementirana](https://cloud.githubusercontent.com/assets/11404450/15308168/91d195e2-1bda-11e6-8ee3-87b1cdf52c70.jpg)

commit IDs:
c9df18a86da73ca5d6808713d845fb73e55b4bea
7e50c6be994bea81829b1996cca4d4f68d7ecddf

Koraci za reproduciranje problema:
1. Pokretanje desktop aplikacije "Inventura"
2. Logiranje u aplikaciju sa pristupnim podacima

Dobijeni rezultat:
Dobijeni rezultat je glavni interfejs bez navedenog funkcionalnog zahtjeva.

Očekivani rezultat:
Očekivani rezultat bi bio glavni interfejs sa nekom opcijom na meniju ili nekim dugmetom "Evidencija artikla" unutar kojeg možemo izabrati artikal što predstavlja ulaz u ovaj F.Z.

**Comment by Hadziarapovic** [comment]
Prethodno smo ga imenovali sa pregled stanja na skladistu. Preimenovan je.

**Comment by Hadziarapovic** [comment]
Ovdje se radi o inventuri, odnosno izvjestaju o artiklima nakon zavrsene inventure. Prikazuje se kojeg artikla ima vise, manje u odnosu na skladiste i to se prikazuje u obliku tabele. Na taj vid evidencije se misli. Svaka druga evidencija o artiklima je na pocetnom interfejsu u meniju Skladiste->Prikaz stanja na skladistu.
