### ISSUE TITLE
Nejasna poruka pri pokušaju modifikacije korisnika

### ISSUE THREAD

**Issue by kprses** [SoftverInzenjeringETFSA/Si2015Tim4#82]
Komponenta:
ModifikacijaKorisnikaGUI

commit ID:
c9df18a86da73ca5d6808713d845fb73e55b4bea

Opis problema:
Kada se pokuša izvršiti modifikacija korisnika pokazuje se nejasna poruka. Na osnovu te povratne informacije ne znamo da li su se podaci korisnika uspješno promijenili ili nisu.

Koraci za reproduciranje problema:
1. Pokretanje desktop aplikacije "Inventura" sa privilegijom "Sef"
2. U menubaru se izabere opcija Administracija -> Korisnici -> Modifikacija
3. Odabere se korisnik kojeg želimo mijenjati
4. Popunimo sve podatke o korisniku
5. Kliknemo na dugme "Sačuvaj"

Dobijeni rezultat:
Rezultat Message Box sa nejasnom porukom

![mofifikacija](https://cloud.githubusercontent.com/assets/11404450/15308533/e6514faa-1bde-11e6-9330-20d232e2ee6a.jpg)

Ocekivani rezultat:
Poruka da su podaci za korisnika uspješno ili bezuspješno modificirani.

**Comment by sibrahimpa1** [comment]
Isto kao i issue #39.
