### ISSUE TITLE
Akcija "zaključi dokument" ne radi očekivano

### ISSUE THREAD

**Issue by kprses** [SoftverInzenjeringETFSA/Si2015Tim4#84]
Komponenta: izlazniDokument

commit ID:
bc1ab5e

Opis problema:
Ukoliko napravimo izlaz ili otpis nekog artikla i unesemo količinu koja je veća od trenutne količine na stanju za izabrani artikal nakon klika na dugme "Zaključi dokument" mi zapravo postavljamo stanje artikla na skladištu.

Koraci za reproduciranje problema:
1. Pokretanje desktop aplikacije "Inventura" sa privilegijom "Sef"
2. U menubaru se izabere opcija Dokumenti -> Kreiraj dokument
3. Odabere se artikal za koji pravimo izlaz
4. Unesemo količinu koja je veća od količine na skladištu
5. Kliknemo na dugme "Dodaj >>"
6. Klikenamo na dugme "Zaključi dokument"

Dobijeni rezultat:
U skladištu na stanju sada imamo količinu koja je unesena na prethodnom izlazu.

Stanje artikla na sladištu prije zaključivanja dokumenta:
![izlazartikla](https://cloud.githubusercontent.com/assets/11404450/15308874/fbc62aec-1be1-11e6-926a-e20812e4acd2.jpg)

Stanje artikla na sladištu nakon zaključivanja dokumenta:
![stanjenakonizlaza](https://cloud.githubusercontent.com/assets/11404450/15308898/264581fa-1be2-11e6-9b3f-3872ef7d9e9b.jpg)

Očekivani rezultat:
Poruka o pogrešno unesenoj količini npr. "Nema dovoljno komada artikla na stanju" ili ako artikli zaista postoje a nisu zavedeni da se na stanju prikaže u minusu x komada ili nešto slično.

**Comment by sibrahimpa1** [comment]
Poenta kreiranja izlaznog dokumenta je upravo ono sto si ti naveo. Ako uneses manju kolicinu nego sto je bila, azurirat ce se stanje na skladistu, i kreirati dokument manjka ( provjeri u dokumentima), a ako se unese vise nego na skladistu, kreira se dokument viska, te se njima pristupa kroz glavi meni -> Dokumenti -> prikazi dokumente viska/manjka.

**Comment by kprses** [comment]
Nisam rekao da je bug kada se unese količina manja nego što je na stanju tada funkcioniše sve kako treba, nego kada se unese količina koja je veća od stanja jednostavno tom vrijednošću se postavi novo stanje na skladišu na vrijednost koju smo unijeli i to stanje je veće nego prethodno, a napravili smo izlaz artikala iz skladišta. U dokumentaciji piše da izlaz smanjuje stanje na skladištu a ulaz povećava. U ovom slučaju smo napravili izlaz koji je povećao stanje na skladištu što je u kontradikciji sa dokumentacijom.
