### ISSUE TITLE
3.2.10 Kreiranje izvještaja tipa otpis nije u skladu sa SRS-om

### ISSUE THREAD

**Issue by kprses** [SoftverInzenjeringETFSA/Si2015Tim4#86]
Komponenta: izlazniDokument

commit ID:
bc1ab5e

Opis problema:
Kreiranje izvještaja/dokumenta tipa otpis nije u skladu sa SRS-om zbog toga što je u SRS-u navedeno da su ulazi za ovu akciju cijena i bar kod, a to nije slučaj na formi. Na formi je potrebno samo odabrati artikal uz koji stoji količina na skladištu te je kao ulaz potrebno unijeti samo količinu.

SRS F.Z. 3.2.10:
![otpissrs](https://cloud.githubusercontent.com/assets/11404450/15309671/3fea7d3e-1be9-11e6-8dd5-1ec6c9f09ac0.jpg)

Forma za kreranje izvještaja/dokumenta:
![ulazuformi](https://cloud.githubusercontent.com/assets/11404450/15309705/87679b9c-1be9-11e6-90c6-13056cb86198.jpg)

Koraci za reproduciranje problema:
1. Pokretanje desktop aplikacije "Inventura" sa privilegijom "Sef"
2. U menubaru se izabere opcija Dokumenti -> Kreiraj dokument

Dobijeni rezultat:
Forma bez mogućnosti unosa ulaznih parametara specificiranih u SRS-u

Očekivani rezultat:
Očekivani rezultat je forma u kojoj je moguće unijeti parametre specificirane u SRS-u da bi se kreirao željeni izvještaj

**Comment by sibrahimpa1** [comment]
Odabirom odgovarajuceg artikla iz lijeve tabele se automatski pokupe podaci koji su spomenuti u SRS dokumentu, te je na ovaj nacin olaksan sam proces inventure jer korisnik ne mora traziti odredjene podatke, te unositi ih rucno.
