### ISSUE TITLE
Neslaganje sa NFZ 5. iz SRS-a

### ISSUE THREAD

**Issue by emhuskic** [SoftverInzenjeringETFSA/Si2015Tim4#87]
Komponenta:
Inventura

commit ID:
8417bbc

Opis problema:
U SRS-u je navedeno sljedeće:
NFZ 5. Potrebno je da postoji opcija za "pomoc" koja ce pruziti korisnicima osnovne
informacije o funkcionalnostima interfejsa na kojem korisnici rade. 
Nije implementirano.

Koraci reproduciranja problema:
1. Pokretanje aplikacije
2. Prijava pomocu podataka bilo koji username i password

Screenshot iz SRS-a:http://pokit.org/get/?90153316fe98d13e9ce33b50a8a86fc7.jpg

Očekivani rezultat:
Prikaz opcije za "pomoc".

**Comment by Hadziarapovic** [comment]
> 6f54efc
