### ISSUE TITLE
Neslaganje sa N.F.Z 9

### ISSUE THREAD

**Issue by kprses** [SoftverInzenjeringETFSA/Si2015Tim4#89]
Komponenta:
RegistracijaNovogKorisnika
LogInScreen

commit ID:
c9df18a86da73ca5d6808713d845fb73e55b4bea
cc43473d06d1801275624116e24ce9bbcf3789e0

Opis problema:
U SRS-u je navedeno sljedeće:
![nfz9](https://cloud.githubusercontent.com/assets/11404450/15404979/484139aa-1e00-11e6-8182-5270a5681fdc.jpg)
Prema SRS-u korisnici pristupaju pomoću korisničkog imena I lozinke, međutim sistem omogućava kreiranje korisnika bez lozinke. Tako da se korsnik može prijaviti u sistem bez lozinke

Koraci reproduciranja problema:
1. Pokretanje aplikacije
2. Prijava u aplikaciju sa privilegijama "Sef"
3. Odabir opcije Administracija -> Korisnici -> Unos
4. Unos svih polja za korisnika osim polja Lozinka

![formapassparazan](https://cloud.githubusercontent.com/assets/11404450/15405045/8de45fdc-1e00-11e6-85ee-1cf4050087f1.jpg)

5. Odjava iz aplikacije
6. Prijava u aplikaciju sa korisnickim imenom (u našem slučaju nekokorime)

![prijavabez](https://cloud.githubusercontent.com/assets/11404450/15405167/11d5d8a2-1e01-11e6-8c0f-9e8a58e88445.jpg)

Stanje u bazi:
![baza](https://cloud.githubusercontent.com/assets/11404450/15405056/9dfc34a8-1e00-11e6-8013-d6a6ddff60ca.jpg)

Očekivani rezultat:
Zabrana unošenja lozinke ili zabrana kreiranja korisnika bez lozinke.

**Comment by sibrahimpa1** [comment]
U ovom NFZ sto si ti naveo nigdje nije navedeno koliko karaktera sifra treba da sadrzi (to se navodi tek u naredna dva NFZ-a a taj si issue vec otvorio tako da je problem u srzi isti).
Dok god govorimo o NFZ-u kojeg si ovdje naveo vrijedi da je korisnik vrlo lahko mogao staviti lozinku da bude prazna, dok vec u prethodnom bug-u koji si otvorio ima smisla pricati o tome da li je lozinka blank ili nije. Tako da ovaj bug je invalidan iz vise razloga, prvo jer je dio drugog problema koji si vec naveo, a drugo jer ovdje nema nikakvog neslaganja sa navedenim NFZ-om: korisnik se zaista loguje preko navedenih podataka, i spasavaju se u bazu.
Ocekivani rezultat koji si naveo spada u issue #88 koji si otvorio, jer se tek u tim NFZ-ma definise koliko lozinka treba imati karaktera. Bug bi bio 'fali validacija na polju da unosenje lozinke koja mora biti minimalno 10 karaktera', a ti nisi izricito to naveo, ali hvala u svakom slucaju sto si nas napomenuo.
