### ISSUE TITLE
Validacija lozinke pri unosu korisnika nije u skladu sa NFZ 11

### ISSUE THREAD

**Issue by kprses** [SoftverInzenjeringETFSA/Si2015Tim4#90]
Komponenta:
RegistracijaNovogKorisnika

commit ID:
c9df18a

Opis problema:
U SRS-u je pod NFZ 11 stoji da lozinka treba sadrzavati minimalno 10 karaktera, u sistemu je moguce kreirati lozinku za korisnika koja je kraca od 10 karaktera

![image](https://cloud.githubusercontent.com/assets/11404450/15406265/1c67601a-1e06-11e6-985a-0d3fd3d28fb7.png)

Koraci reproduciranja problema:
1. Pokretanje aplikacije
2. Prijava u aplikaciju sa privilegijama "Sef"
3. Odabir opcije Administracija -> Korisnici -> Unos
4. Popunjavanje svih polja (u polje lozinka unos teksta koji je kraci od 10 karaktera)

Očekivani rezultat:
Poruka u kojoj se korisnik obavjestava da je minimalan broj karaktera za lozinku 10.

**Comment by sibrahimpa1** [comment]
Issue je duplikat, tacnije da si prelistao vidio bi da je vec 3 puta navedeno :)
#71, #46, #38 :)
