### ISSUE TITLE
Artikli koji idu na komad moguće unjeti količinu koja nije cijeli broj

### ISSUE THREAD

**Issue by muhamed-smajevic** [SoftverInzenjeringETFSA/Si2015Tim4#91]
Komponenta:
InventuraGUI
d09acb664c912fe101689c637ec8c28f7a09a45a

Opis problema:
Za artikle koji se tretiraju po komadu moguće unijeti količinu koja nije cijeli broj.

Koraci reproduciranja problema:
1. Pokretanje aplikacije
2. Odabir opcije Inventura -> Započni novu
3. Očitavanje artikla koji se vodi po komadu (barkod: 3)
4. Unos izbrojane količine kao broj koji nije cijeli.

Unos:
![image](https://cloud.githubusercontent.com/assets/8416233/15442615/a37ba61a-1ee2-11e6-82ef-5771a54add7e.png)

Rezultat:
![image](https://cloud.githubusercontent.com/assets/8416233/15442622/af4c1a6a-1ee2-11e6-92b4-f60dc66bcd60.png)

Očekivani rezultat:
Poruka u kojoj se korisnik obavještava da izbrojana količina mora biti cijeli broj.

**Comment by Hadziarapovic** [comment]
Popravljeno.
