### ISSUE TITLE
Unos količine u kreiranju dokumenta ne prihvata broj

### ISSUE THREAD

**Issue by muhamed-smajevic** [SoftverInzenjeringETFSA/Si2015Tim4#92]
Komponenta:
Kreiranje izvještaja

commitID:
29ba05ffecacb50c0eacc31c50e58545fa4b0eec

Opis problema:
U polje "Unesite količinu" nijedan uneseni broj se ne prihvata. Dobija se greška "Količina sadrži samo brojeve" iako je unesen broj.

Koraci reproduciranja problema:
1. Pokretanje aplikacije
2. Odabir opcije Dokumenti -> Kreiraj dokument
3. Odabir nekog artikla.
4. Popunjavanje polja "Unesite količinu" sa nekim cijelim brojem.

Unos:
![image](https://cloud.githubusercontent.com/assets/8416233/15442957/d70f953e-1ee4-11e6-82ef-26061492207e.png)

Rezultat:
![image](https://cloud.githubusercontent.com/assets/8416233/15442968/e1519c18-1ee4-11e6-89fa-77b58613abd6.png)

Očekivani rezultat:
Nastavak kreiranja dokumenta.

**Comment by Hadziarapovic** [comment]
Ja sam upravo to isto odradila, i regularno se dodaje na listu dodanih artikala. 

![image](https://cloud.githubusercontent.com/assets/11289714/15444470/5b695674-1ef1-11e6-9cc0-53f62b058194.png)
